In [1]:
import time
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
from pandas.api.types import is_numeric_dtype
from functools import reduce
from pandas.api.types import is_numeric_dtype
from itertools import groupby

In [2]:
df = pd.read_csv('../data/Breast/Breast-main.csv')

In [3]:
df_headers = list(df)
concept = df_headers[-1]
concept

'class'

In [4]:
#all unique concepts
concept_list = df[concept].unique()
concept_list

array(['no-recurrence-events', 'recurrence-events'], dtype=object)

In [5]:
#calculating cases by concepts and making sets
temp_list = []
goal_list = []
for item in concept_list:
    for index, row in df.iterrows():
        if row[concept] == item:
            temp_list.append(index+1)
    goal_list.append(temp_list)
    temp_list = []

In [6]:
print(goal_list,)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196], [197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277]]

In [7]:
attributes = list(df)
attributes

['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'class']

In [8]:
case_list = []

In [9]:
#Loop through all the attributes except last 2 - Concept and sort_col
for item in attributes[:-1]:
    #check for non numeric columns
    temp = df[item].unique()
    for i in temp:
        case = item + "," + str(i)
        case_list.append(case)

In [10]:
case_list

['a1,30-39',
 'a1,40-49',
 'a1,60-69',
 'a1,50-59',
 'a1,70-79',
 'a1,20-29',
 'a2,premeno',
 'a2,ge40',
 'a2,lt40',
 'a3,30-34',
 'a3,20-24',
 'a3,15-19',
 'a3,0-4',
 'a3,25-29',
 'a3,50-54',
 'a3,10-14',
 'a3,40-44',
 'a3,35-39',
 'a3,5-9',
 'a3,45-49',
 'a4,0-2',
 'a4,6-8',
 'a4,9-11',
 'a4,3-5',
 'a4,15-17',
 'a4,12-14',
 'a4,24-26',
 'a5,no',
 'a5,yes',
 'a6,3',
 'a6,2',
 'a6,1',
 'a7,left',
 'a7,right',
 'a8,left_low',
 'a8,right_up',
 'a8,left_up',
 'a8,right_low',
 'a8,central',
 'a9,no',
 'a9,yes']

In [11]:
temp_list = []
att_val_list = []
for item in case_list:
    a,b = item.split(",") #a = attribute and b = value

    for index, row in df.iterrows():
        if row[a] == b:
            temp_list.append(index+1)

    att_val_list.append(temp_list)
    temp_list = []

In [12]:
#Creating data for case and att-value list
data = {'Cases': case_list, 'att_val': att_val_list}

In [13]:
df2 = pd.DataFrame(data)
df2

           Cases                                            att_val
0       a1,30-39  [1, 23, 36, 52, 75, 78, 91, 100, 108, 117, 119...
1       a1,40-49  [2, 3, 5, 9, 10, 11, 15, 17, 26, 29, 39, 40, 4...
2       a1,60-69  [4, 6, 8, 13, 16, 19, 22, 28, 30, 42, 43, 59, ...
3       a1,50-59  [7, 12, 14, 18, 20, 21, 24, 25, 27, 31, 32, 33...
4       a1,70-79                              [54, 55, 56, 88, 126]
5       a1,20-29                                               [64]
6     a2,premeno  [1, 2, 3, 5, 7, 9, 10, 11, 15, 17, 18, 23, 24,...
7        a2,ge40  [4, 6, 8, 12, 14, 19, 20, 21, 22, 28, 30, 31, ...
8        a2,lt40                             [13, 16, 51, 149, 154]
9       a3,30-34  [1, 15, 16, 18, 19, 20, 30, 36, 40, 46, 59, 96...
10      a3,20-24  [2, 3, 8, 10, 27, 41, 49, 50, 52, 54, 61, 68, ...
11      a3,15-19  [4, 6, 17, 22, 32, 38, 51, 53, 60, 74, 83, 84,...
12        a3,0-4                   [5, 11, 37, 57, 63, 88, 91, 201]
13      a3,25-29  [7, 12, 14, 23, 26, 28, 42, 47, 48, 65, 67, 72...
14      a3,50-54               [9, 45, 70, 146, 190, 225, 245, 247]
15      a3,10-14  [13, 33, 34, 35, 39, 44, 62, 66, 71, 76, 77, 8...
16      a3,40-44  [21, 24, 29, 31, 55, 56, 90, 108, 123, 132, 13...
17      a3,35-39  [25, 64, 69, 86, 115, 130, 131, 152, 159, 178,...
18        a3,5-9                                  [43, 58, 75, 138]
19      a3,45-49                                    [144, 145, 224]
20        a4,0-2  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
21        a4,6-8  [127, 128, 133, 145, 170, 181, 188, 236, 240, ...
22       a4,9-11                [130, 131, 225, 239, 241, 257, 267]
23        a4,3-5  [132, 136, 137, 141, 142, 147, 151, 155, 156, ...
24      a4,15-17                     [150, 152, 165, 221, 235, 270]
25      a4,12-14                                    [186, 238, 255]
26      a4,24-26                                              [259]
27         a5,no  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
28        a5,yes  [127, 128, 129, 130, 131, 132, 141, 142, 145, ...
29          a6,3                                                 []
30          a6,2                                                 []
31          a6,1                                                 []
32       a7,left  [1, 3, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17,...
33      a7,right  [2, 4, 5, 10, 20, 23, 25, 28, 29, 31, 32, 34, ...
34   a8,left_low  [1, 3, 6, 7, 8, 9, 12, 16, 17, 18, 19, 21, 22,...
35   a8,right_up  [2, 13, 14, 20, 45, 49, 56, 58, 64, 99, 108, 1...
36    a8,left_up  [4, 10, 15, 24, 25, 26, 28, 31, 34, 35, 36, 44...
37  a8,right_low  [5, 52, 62, 65, 67, 74, 75, 85, 88, 96, 103, 1...
38    a8,central  [11, 37, 38, 43, 57, 61, 78, 80, 91, 112, 126,...
39         a9,no  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
40        a9,yes  [128, 130, 131, 132, 135, 137, 138, 139, 144, ...

In [14]:
df3 = df2

In [15]:
import pylab as pl

In [16]:
def findGoalIntersect(goal):
    goalIntersect = []
    
    for index, row in df3.iterrows():
        #List containing intersection of (a,v) pairs and goal
        goalIntersect.append(set(row['att_val']).intersection(set(goal)))
          
    #Check if goal_intersect column exists
    if 'goal_intersect' in df3:
        df3['goal_intersect'] = goalIntersect
    else:
        #Insert new column with the recent iteration
        df3.insert(2, 'goal_intersect', goalIntersect)

In [17]:
def updateGoalIntersect(goal):
    for index, row in df3.iterrows():
        if row['goal_intersect'] != set():
            row['goal_intersetct'] = set(row['att_val']).intersection(set(goal))

In [18]:
def findCases(df3):
    case_to_be = []
    #Find the cases with maximum goal coverage
    m = max(df3['goal_intersect'], key=len)
    possible_cases = [i for i, j in enumerate(df3['goal_intersect'].tolist()) if j == m]
    
    #Index of the case covering max goal and having min no. of elements
    new_df = df3.iloc[possible_cases,:]
    
    m1 = min(new_df['att_val'], key=len)
    
    for index,row in new_df.iterrows():
        if row['att_val'] == m1:
            case_to_be.append(index)
   
    return case_to_be[0]

In [19]:
def combineInterval(test_condition):
    
    test_num = [] #This will contain the conditions having interval
    test_str = [] #This will contain the conditions having no interval
    
    #Loop through to seprate contions having intervals and no intervals
    for item in test_condition:
        if ".." in item:
            test_num.append(item)
        else:
            test_str.append(item)
   
    #Group the conditions having interval based on same attributes
    grouped = [list(g) for k, g in groupby(test_num, lambda s: s.partition(',')[0])]
    
    final_list = []
    
    #Actually combining the intervals
    for list1 in grouped:
        greatest = 0
        smallest = 0
        for item in list1:
            part1,part2 = item.split(",")
            start,stop = part2.split("..")
            start = float(start)
            stop = float(stop)

            if greatest == 0 and smallest == 0:
                greatest = start
                smallest = stop

            if start > greatest:
                greatest = float(start)

            if stop < smallest:
                smallest = float(stop)

        con_tmp = part1 + "," + str(greatest) + ".." + str(smallest)
        final_list.append(con_tmp)  
            
    actual_condition = final_list + test_str
    
    return actual_condition

In [20]:
def dropCondition(condition,current_goal):
    
    for item in range(0,len(condition)):
        temp_att_val = []
        temp_cond = condition.copy() #use list.copy() as equal operator simply copies over the reference
        temp_cond.remove(condition[item])
       
        #temp_cond contains the elements after removing the current element
        for i in temp_cond:
            if i is not None:
                location = df3.index[df3['Cases'] == i].tolist()
                element = df3['att_val'].loc[location[0]]
                temp_att_val.append(set(element))
          
        #temp_att_val contains the actual value set of the corresponding cases
        #Find the intersection if the set has more than one element, otherwise no need
        if len(temp_att_val) > 1:
            intersection = set.intersection(*temp_att_val)
        
            #if the set still remains a subset of the original goal after removing current element
            #then set the current element to None as we want to drop this later
            if intersection.issubset(current_goal):
                condition[item] = None
    
    condition = [x for x in condition if x is not None]
   
    return condition

In [21]:
def stepAlgo(df3,selected_case,current_goal,B,condition,concept_curr):
    
    rule_set = []
    original_goal = current_goal.copy()
    
    
    while current_goal != set():
        #Check if the selected case is a subset of the current goal
        #List of current case
        A = df3['att_val'].loc[selected_case] 

        if B == set():
            #Copy over the current set elements to B
            for i in range(len(A)):
                B.add(A[i])

        #Elements of intersection of current and previous set
        A = set(A).intersection(B)
        B = A.copy()
        
        print("Intersection set: ", A)
        #Check if intersecting elements are subset of Goal
        if A.issubset(original_goal):
            print("yes")
            #Current goal is updated after discarding the already covered goal by new rule
            if len(A) != 0:
                current_goal = set(current_goal) - df3['goal_intersect'].loc[selected_case]
            else:
                current_goal = set()
            

            #Extract the current case
            curr_case = df3['Cases'].loc[selected_case]
            #Add the conditions of a Rule
            condition.append(curr_case)
            
            #Check for possibility of dropping conditions
            if len(condition) > 1:
                condition = dropCondition(condition,original_goal)
            
            #Combine the interval
            if len(condition) > 1:
                condition = combineInterval(condition)
            

            #Join conditions
            cond = ""
            for item in condition:
                cond = cond + "(" + str(item) + ")" + " & "

            cond = cond[:-2] + "->"
            rule = cond + " (" + concept + "," + str(concept_curr) + ")"
            rule_set.append(rule)
            
            
            #Reset everythng and continue for covering rest of the goal
            condition = []
            B = set()
            findGoalIntersect(current_goal)
            selected_case = findCases(df3)
            

        #If not a subset of current goal
        else:
            #Assign empty set for the selected case for next iteration
            df3['goal_intersect'].loc[selected_case] = set()
           
            #Extract the current case
            curr_case = df3['Cases'].loc[selected_case]
            #Add the case to the condition list
            condition.append(curr_case)
            
            #Check for Range overlapping of the remaining cases
            if ".." in curr_case:
                second_part = curr_case.split(',')[1]
                start = float(second_part.split('..')[0])
                end = float(second_part.split('..')[1])
                for index, row in df3.iterrows():
                    if ".." in row['Cases']:
                        part2 = row['Cases'].split(',')[1]
                        start1 = float(part2.split('..')[0])
                        end1 = float(part2.split('..')[1])

                        #Assign blank set for cases with overlapping ranges
                        if set((pl.frange(start,end))).issubset(pl.frange(start1,end1)) == True:
                            if start == start1 and end <= end1:
                                row['goal_intersect'] = set()
            
            updateGoalIntersect(A.intersection(current_goal))
            selected_case = findCases(df3)
                        
    return rule_set

In [22]:
#concept_list and goal_list has 1:1 mapping
final_rules = []
start_time = time.time()

#Running algorithm for all the goals/concepts
for i in range(0,len(goal_list)):
    findGoalIntersect(goal_list[i])
    condition = []
    B = set()
    selected_case = findCases(df3)
    
    rule_set = stepAlgo(df3,selected_case,goal_list[i],B,condition,concept_list[i])
    final_rules.append(rule_set)
    print("End of goal")
    
elapsed_time = time.time() - start_time

Intersection set:  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 133, 134, 135, 136, 137, 138, 139, 140, 143, 144, 146, 148, 149, 152, 153, 154, 155, 157, 158, 159, 160, 162, 163, 164, 166, 167, 169, 173, 174, 175, 176, 177, 180, 181, 182, 183, 184, 186, 187, 189, 191, 192, 193, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 220, 222, 224, 226, 227, 228, 230, 231, 232, 234, 236, 239, 244, 245, 246, 247, 250, 253, 254, 256, 260, 261, 263, 273, 274, 275, 276, 277}
Intersection set:  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 134, 135, 138, 139, 140, 143, 144, 146, 148, 149, 153, 154, 157, 158, 159, 160, 162, 166, 167, 169, 173, 174, 175, 177, 180, 182, 183, 184, 187, 189, 191, 193, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 222, 224, 228, 230, 231, 232, 244, 245, 246, 247, 250, 256, 260, 261, 263, 273, 274, 275}
Intersection set:  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 134, 140, 143, 148, 149, 154, 157, 158, 159, 166, 169, 174, 175, 182, 184, 189, 191, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 218, 230, 231, 232, 244, 246, 247, 256, 260, 273, 275}
Intersection set:  {1, 2, 3, 5, 7, 9, 10, 11, 15, 17, 18, 23, 24, 25, 26, 27, 29, 32, 33, 36, 39, 40, 44, 47, 48, 49, 50, 52, 53, 61, 62, 64, 65, 66, 67, 72, 74, 75, 78, 79, 80, 85, 90, 91, 95, 96, 99, 100, 103, 104, 105, 106, 107, 108, 109, 113, 114, 115, 117, 119, 140, 148, 157, 159, 166, 169, 184, 189, 195, 197, 198, 200, 201, 202, 203, 204, 205, 207, 208, 212, 214, 215, 216, 230, 231, 232, 244, 246, 260, 273}
Intersection set:  {1, 3, 260, 7, 9, 11, 140, 15, 17, 18, 273, 148, 24, 26, 27, 157, 159, 33, 36, 39, 40, 169, 44, 52, 53, 61, 189, 65, 195, 197, 198, 200, 202, 75, 203, 205, 78, 79, 212, 85, 215, 95, 99, 100, 104, 232, 107, 244, 117, 246}
Intersection set:  set()
yes
End of goal
Intersection set:  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 129, 133, 134, 136, 140, 141, 142, 143, 145, 148, 149, 150, 151, 152, 154, 156, 157, 158, 159, 161, 163, 164, 166, 169, 170, 171, 174, 175, 182, 184, 185, 188, 189, 191, 192, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 218, 221, 223, 225, 226, 230, 231, 232, 235, 237, 242, 243, 244, 246, 247, 248, 249, 253, 254, 256, 257, 258, 260, 262, 264, 267, 270, 273, 275, 276, 277}
Intersection set:  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 133, 134, 136, 140, 143, 148, 149, 152, 154, 157, 158, 159, 163, 164, 166, 169, 174, 175, 182, 184, 189, 191, 192, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 218, 226, 230, 231, 232, 244, 246, 247, 253, 254, 256, 260, 273, 275, 276, 277}
Intersection set:  {1, 2, 3, 5, 7, 9, 10, 11, 15, 17, 18, 23, 24, 25, 26, 27, 29, 32, 33, 36, 39, 40, 44, 47, 48, 49, 50, 52, 53, 61, 62, 64, 65, 66, 67, 72, 74, 75, 78, 79, 80, 85, 90, 91, 95, 96, 99, 100, 103, 104, 105, 106, 107, 108, 109, 113, 114, 115, 117, 119, 133, 136, 140, 148, 157, 159, 163, 164, 166, 169, 184, 189, 192, 195, 197, 198, 200, 201, 202, 203, 204, 205, 207, 208, 212, 214, 215, 216, 226, 230, 231, 232, 244, 246, 260, 273}
Intersection set:  {1, 3, 260, 133, 7, 9, 11, 140, 15, 17, 18, 273, 148, 24, 26, 27, 157, 159, 33, 36, 39, 40, 169, 44, 52, 53, 61, 189, 65, 195, 197, 198, 200, 202, 75, 203, 205, 78, 79, 212, 85, 215, 95, 99, 100, 104, 232, 107, 244, 117, 246}
Intersection set:  {1, 3, 260, 7, 9, 11, 140, 15, 17, 18, 273, 148, 24, 26, 27, 157, 159, 33, 36, 39, 40, 169, 44, 52, 53, 61, 189, 65, 195, 197, 198, 200, 202, 75, 203, 205, 78, 79, 212, 85, 215, 95, 99, 100, 104, 232, 107, 244, 117, 246}
Intersection set:  set()
yes
End of goal

In [23]:
print("Time to run the algorithm: ", round(elapsed_time, 3), "Sec")
print("\n")
print(*final_rules, sep='\n')

with open('../data/Breast/Rules/Breast_main.txt', 'w') as f:
    for item in final_rules:
        f.write("%s\n" % item)

Time to run the algorithm:  0.451 Sec


['(a7,left) & (a7,right) -> (class,no-recurrence-events)']
['(a7,left) & (a7,right) -> (class,recurrence-events)']